<a href="https://colab.research.google.com/github/Sumit-Kumar-Dash/PyTorch/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch

In [ ]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121

**CUDA** is a programming model and computing toolkit developed by NVIDIA.
It enables you to perform compute-intensive operations faster by parallelizing tasks across GPUs.
CUDA is the dominant API used for deep learning although other options are available, such as OpenCL.
PyTorch provides support for CUDA in the torch

CUDA stands for Compute Unified Device Architecture.

It is a parallel computing platform and programming model developed by NVIDIA.

It allows developers to use the parallel processing power of Nvidia GPUs for general computing applications.

PyTorch is a popular deep learning framework that supports CUDA.
  
To use CUDA in PyTorch, you need to have a Nvidia GPU and the CUDA toolkit installed. Once you have that, you can use the **torch.cuda** library to set up and run CUDA operations.

The torch.cuda library provides a number of functions for working with CUDA, including:


*  **torch.cuda.is_available()** - Checks if CUDA is available.
*  **torch.cuda.device_count()** - Returns the number of CUDA devices
*  **torch.cuda.current_device()** - Returns the current CUDA device.
*  **torch.cuda.set_device()** - Sets the current CUDA device.
*  **torch.cuda.FloatTensor** - Creates a float tensor on the current CUDA device
*  **torch.cuda.LongTensor** - Creates a long tensor on the current CUDA device

You can also use the torch.cuda.synchronize() function to wait for all CUDA operations to complete.
Here is an example of how to use CUDA in PyTorch:
Python

CUDA can be used to accelerate a variety of PyTorch operations, including:
Convolutional neural networks (CNNs), Recurrent neural networks (RNNs), Long short-term memory (LSTM) networks, Gated recurrent units (GRUs), and Attention mechanisms.

If you are using PyTorch for deep learning, it is worth considering using CUDA to accelerate your training and inference.



In [4]:
import torch

# Check if CUDA is available
if torch.cuda.is_available():
    # Set the current CUDA device
    torch.cuda.set_device(0)

    # Create a float tensor on the current CUDA device
    x = torch.tensor([1, 2, 3])

    # Perform an operation on the tensor
    y = x * 2

    # Print the result
    print(y)

tensor([2, 4, 6])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9809, 0.4609, 0.3755],
        [0.2683, 0.5050, 0.5514],
        [0.2361, 0.8977, 0.4602],
        [0.4461, 0.3793, 0.8545],
        [0.4981, 0.7001, 0.2085]])


**What is tensor?**

A kind of data structure => multidimensional arrays or matrices

With tensors you enocode all your parameters.

**Type Conversions**

  Conversions from one datatype to another.
  
  Conversions from torch tensors to numpy arrays and vice versa.


# Tensors

In [4]:
import torch

In [14]:
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cpu'

In [10]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [11]:
torch.tensor([1,2,3]).shape

torch.Size([3])

In [6]:
basic_tensor = torch.tensor([[1,2,3],[1,3,5]])
basic_tensor

tensor([[1, 2, 3],
        [1, 3, 5]])

In [7]:
basic_tensor.device

device(type='cpu')

In [8]:
basic_tensor.dtype

torch.int64

In [9]:
basic_tensor.shape # 2 rows and 3 cols

torch.Size([2, 3])

In [13]:
basic_tensor.requires_grad
#Is True if gradients need to be computed for this Tensor, False otherwise.
#The fact that gradients need to be computed for a Tensor do not mean that the grad attribute will be populated, see is_leaf for more details

False

In [17]:
tensor = torch.tensor([[1,2,3],[11,22,33]],
                      dtype=torch.float,
                      device=device,
                      requires_grad=True)
tensor

tensor([[ 1.,  2.,  3.],
        [11., 22., 33.]], requires_grad=True)

In [16]:
tensor.dtype

torch.float32

In [18]:
tensor.requires_grad

True

# Others common used Tensors

In [19]:
x = torch.empty(size=(3,3))
x

tensor([[-8.8571e+31,  4.3592e-41, -7.0902e+25],
        [ 3.1469e-41,  4.4842e-44,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -9.7767e-26]])

In [20]:
x = torch.zeros(size=(2,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
x = torch.ones(size=(2,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [22]:
x = torch.rand(size=(2,3))
x

tensor([[0.4742, 0.3759, 0.6747],
        [0.9440, 0.6288, 0.7551]])

In [24]:
x = torch.eye(2) # identity matrix
x

tensor([[1., 0.],
        [0., 1.]])

In [25]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [27]:
x = torch.arange(start=2,end=9.5,step=1.5)
x

tensor([2.0000, 3.5000, 5.0000, 6.5000, 8.0000])

In [32]:
x = torch.linspace(start=2,end=9,steps=5)
x

tensor([2.0000, 3.7500, 5.5000, 7.2500, 9.0000])

In [33]:
x = torch.rand(size=(2,3)).normal_(mean=0,std=1)
x

tensor([[-1.8877,  0.6061,  0.1606],
        [-0.9650, -0.2729, -0.8816]])

In [35]:
x = torch.rand(size=(2,3)).uniform_(3,5)
x

tensor([[3.4436, 4.6304, 4.5448],
        [4.5510, 4.4155, 4.8361]])

In [38]:
x = torch.diag(torch.ones(10))
x

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
x = torch.diag(6*torch.ones(10))
x

tensor([[6., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 6., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 6., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 6., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 6., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 6., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 6., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 6., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 6.]])

# Conversions

In [40]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

In [41]:
x.bool()

tensor([False,  True,  True,  True])

In [42]:
x.float()

tensor([0., 1., 2., 3.])

In [43]:
x.short()

tensor([0, 1, 2, 3], dtype=torch.int16)

In [44]:
x.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [45]:
x.long()              #torch.int64

tensor([0, 1, 2, 3])

In [46]:
x.half()              #torch.float16

tensor([0., 1., 2., 3.], dtype=torch.float16)

In [47]:
x.float()             #torch.float32

tensor([0., 1., 2., 3.])

In [48]:
x.double()

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [49]:
import numpy as np
np_array = np.array([[1,2,3], [1,2,3]])

np_array

array([[1, 2, 3],
       [1, 2, 3]])

In [50]:
tensor  = torch.from_numpy(np_array)
tensor

tensor([[1, 2, 3],
        [1, 2, 3]])

In [51]:
tensor.numpy()

array([[1, 2, 3],
       [1, 2, 3]])

# Mathematical Operations

In [52]:
x = torch.arange(start=1, end=10, step=4)
y = torch.arange(start=5, end=15, step=4)

In [53]:
x.shape,y.shape

(torch.Size([3]), torch.Size([3]))

In [54]:
x

tensor([1, 5, 9])

In [55]:
y

tensor([ 5,  9, 13])

In [56]:
x+y

tensor([ 6, 14, 22])

In [57]:
x-y

tensor([-4, -4, -4])

In [58]:
x*y # element wise multiplication

tensor([  5,  45, 117])

In [76]:
torch.dot(x,y) # dot product

tensor(167)

In [59]:
x/y # element wise multiplication

tensor([0.2000, 0.5556, 0.6923])

In [64]:
z = torch.ones(3)
z

tensor([1., 1., 1.])

In [65]:
z = z+x
z

tensor([ 2.,  6., 10.])

In [67]:
z = torch.ones(3)
z.add_(x) #inplace addition

tensor([ 2.,  6., 10.])

In [68]:
x.pow(2)

tensor([ 1, 25, 81])

In [69]:
x**2

tensor([ 1, 25, 81])

In [70]:
x > 2

tensor([False,  True,  True])

In [71]:
# matrix multiplication
A = torch.rand(size=(3,5))
B = torch.rand(size=(5,4))
A@B

tensor([[1.5540, 1.6090, 2.3875, 1.7439],
        [1.2445, 1.4806, 1.7885, 1.6200],
        [1.3201, 1.2340, 2.2718, 1.9919]])

In [72]:
A.matmul(B)

tensor([[1.5540, 1.6090, 2.3875, 1.7439],
        [1.2445, 1.4806, 1.7885, 1.6200],
        [1.3201, 1.2340, 2.2718, 1.9919]])

In [75]:
X = torch.rand([3,3])
print(X)
X.matrix_exp()

tensor([[0.5585, 0.5995, 0.5480],
        [0.5544, 0.0019, 0.9622],
        [0.0854, 0.1276, 0.0949]])


tensor([[2.0586, 0.9191, 1.2092],
        [0.8615, 1.2975, 1.3087],
        [0.1759, 0.1807, 1.2179]])

In [77]:
X.matrix_power(2)

tensor([[0.6911, 0.4059, 0.9349],
        [0.3928, 0.4552, 0.3969],
        [0.1265, 0.0635, 0.1786]])

In [78]:
A

tensor([[0.8820, 0.7464, 0.9859, 0.2891, 0.8239],
        [0.6432, 0.2987, 0.5741, 0.4754, 0.9766],
        [0.9565, 0.9093, 0.6655, 0.9801, 0.2183]])

In [79]:
A.shape

torch.Size([3, 5])

In [80]:
A+1

tensor([[1.8820, 1.7464, 1.9859, 1.2891, 1.8239],
        [1.6432, 1.2987, 1.5741, 1.4754, 1.9766],
        [1.9565, 1.9093, 1.6655, 1.9801, 1.2183]])

In [81]:
A-1

tensor([[-0.1180, -0.2536, -0.0141, -0.7109, -0.1761],
        [-0.3568, -0.7013, -0.4259, -0.5246, -0.0234],
        [-0.0435, -0.0907, -0.3345, -0.0199, -0.7817]])

In [82]:
A*5

tensor([[4.4098, 3.7319, 4.9293, 1.4457, 4.1195],
        [3.2159, 1.4934, 2.8707, 2.3772, 4.8828],
        [4.7823, 4.5467, 3.3274, 4.9007, 1.0916]])

In [85]:
C = torch.ones((1,5))
C

tensor([[1., 1., 1., 1., 1.]])

In [86]:
A+C # Broadcasting of matrix

tensor([[1.8820, 1.7464, 1.9859, 1.2891, 1.8239],
        [1.6432, 1.2987, 1.5741, 1.4754, 1.9766],
        [1.9565, 1.9093, 1.6655, 1.9801, 1.2183]])

In [87]:
D = torch.ones((2,5))
D

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [88]:
A+D

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

In [89]:
D = torch.ones((3,1))
D

tensor([[1.],
        [1.],
        [1.]])

In [90]:
A+D

tensor([[1.8820, 1.7464, 1.9859, 1.2891, 1.8239],
        [1.6432, 1.2987, 1.5741, 1.4754, 1.9766],
        [1.9565, 1.9093, 1.6655, 1.9801, 1.2183]])

In [91]:
torch.sum(A) # sum of all elemnts of A

tensor(10.4250)

In [92]:
torch.max(A)

tensor(0.9859)

In [93]:
torch.min(A)

tensor(0.2183)

In [94]:
torch.min(A,dim=1)

torch.return_types.min(
values=tensor([0.2891, 0.2987, 0.2183]),
indices=tensor([3, 1, 4]))

In [95]:
torch.max(A,dim=1) #row wise

torch.return_types.max(
values=tensor([0.9859, 0.9766, 0.9801]),
indices=tensor([2, 4, 3]))

In [96]:
torch.max(A,dim=0) # column wise

torch.return_types.max(
values=tensor([0.9565, 0.9093, 0.9859, 0.9801, 0.9766]),
indices=tensor([2, 2, 0, 2, 1]))

In [98]:
-A

tensor([[-0.8820, -0.7464, -0.9859, -0.2891, -0.8239],
        [-0.6432, -0.2987, -0.5741, -0.4754, -0.9766],
        [-0.9565, -0.9093, -0.6655, -0.9801, -0.2183]])

In [99]:
torch.abs(-A)

tensor([[0.8820, 0.7464, 0.9859, 0.2891, 0.8239],
        [0.6432, 0.2987, 0.5741, 0.4754, 0.9766],
        [0.9565, 0.9093, 0.6655, 0.9801, 0.2183]])

In [100]:
torch.argmax(A)

tensor(2)

In [103]:
torch.argmax(A,dim=1) # row wise

tensor([2, 4, 3])

In [104]:
torch.argmax(A,dim=0) # column wise

tensor([2, 2, 0, 2, 1])

In [101]:
torch.argmin(A)

tensor(14)

In [102]:
torch.mean(A)

tensor(0.6950)

In [105]:
torch.mean(A,dim=0)

tensor([0.8272, 0.6515, 0.7418, 0.5816, 0.6729])

In [107]:
print(A.shape,D.shape)

torch.Size([3, 5]) torch.Size([3, 1])


In [108]:
E=torch.ones(A.shape)
E.shape

torch.Size([3, 5])

In [109]:
A==E

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [110]:
torch.eq(A,E)

tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])

In [111]:
torch.eq(A,A)

tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])

In [112]:
A

tensor([[0.8820, 0.7464, 0.9859, 0.2891, 0.8239],
        [0.6432, 0.2987, 0.5741, 0.4754, 0.9766],
        [0.9565, 0.9093, 0.6655, 0.9801, 0.2183]])

In [113]:
torch.sort(A)

torch.return_types.sort(
values=tensor([[0.2891, 0.7464, 0.8239, 0.8820, 0.9859],
        [0.2987, 0.4754, 0.5741, 0.6432, 0.9766],
        [0.2183, 0.6655, 0.9093, 0.9565, 0.9801]]),
indices=tensor([[3, 1, 4, 0, 2],
        [1, 3, 2, 0, 4],
        [4, 2, 1, 0, 3]]))

In [114]:
torch.clamp(A,min=0.5) #value less than 0.5 will replavce with 0.5

tensor([[0.8820, 0.7464, 0.9859, 0.5000, 0.8239],
        [0.6432, 0.5000, 0.5741, 0.5000, 0.9766],
        [0.9565, 0.9093, 0.6655, 0.9801, 0.5000]])

# Indexing & Slicing

In [1]:
import torch
import numpy as np
import os

In [2]:
x = torch.rand(size=(3,4))
x

tensor([[0.4003, 0.5918, 0.7612, 0.1421],
        [0.5836, 0.2990, 0.3090, 0.7392],
        [0.9195, 0.0915, 0.4065, 0.0626]])

x[rows,cols]

row -> start:stop:step

col -> start:stop:step

In [3]:
x[0,:] # all col of 1st row

tensor([0.4003, 0.5918, 0.7612, 0.1421])

In [4]:
x[:,0] # all row of 1st col

tensor([0.4003, 0.5836, 0.9195])

In [6]:
x[0:2,0:3]

tensor([[0.4003, 0.5918, 0.7612],
        [0.5836, 0.2990, 0.3090]])

In [7]:
x[0:2,0:3:2]

tensor([[0.4003, 0.7612],
        [0.5836, 0.3090]])

In [8]:
x[0,0]

tensor(0.4003)

In [11]:
x[0,0] = 2.312
x

tensor([[2.3120, 0.5918, 0.7612, 0.1421],
        [0.5836, 0.2990, 0.3090, 0.7392],
        [0.9195, 0.0915, 0.4065, 0.0626]])

In [12]:
y = torch.rand(size=(3,4))
torch.cat((x,y),dim=1) #concatenation along rows

tensor([[2.3120, 0.5918, 0.7612, 0.1421, 0.0919, 0.8390, 0.6757, 0.9770],
        [0.5836, 0.2990, 0.3090, 0.7392, 0.1705, 0.7552, 0.8226, 0.8607],
        [0.9195, 0.0915, 0.4065, 0.0626, 0.4448, 0.5817, 0.4482, 0.4136]])

In [13]:
torch.cat((x,y),dim=0) #concatenation along cols

tensor([[2.3120, 0.5918, 0.7612, 0.1421],
        [0.5836, 0.2990, 0.3090, 0.7392],
        [0.9195, 0.0915, 0.4065, 0.0626],
        [0.0919, 0.8390, 0.6757, 0.9770],
        [0.1705, 0.7552, 0.8226, 0.8607],
        [0.4448, 0.5817, 0.4482, 0.4136]])

In [14]:
x.shape

torch.Size([3, 4])

In [16]:
x.reshape(2,6)

tensor([[2.3120, 0.5918, 0.7612, 0.1421, 0.5836, 0.2990],
        [0.3090, 0.7392, 0.9195, 0.0915, 0.4065, 0.0626]])

In [17]:
x.reshape(2,3)

RuntimeError: shape '[2, 3]' is invalid for input of size 12

In [18]:
x.reshape(12,1)

tensor([[2.3120],
        [0.5918],
        [0.7612],
        [0.1421],
        [0.5836],
        [0.2990],
        [0.3090],
        [0.7392],
        [0.9195],
        [0.0915],
        [0.4065],
        [0.0626]])

In [19]:
x.view(-1) # Flattening

tensor([2.3120, 0.5918, 0.7612, 0.1421, 0.5836, 0.2990, 0.3090, 0.7392, 0.9195,
        0.0915, 0.4065, 0.0626])

In [20]:
x.view(-1).shape

torch.Size([12])

In [21]:
# batch flattening
batch = 16
torch.rand((batch,2,5)).view((batch,-1))

tensor([[0.1516, 0.1430, 0.7077, 0.1520, 0.8146, 0.5026, 0.3462, 0.0611, 0.4088,
         0.8639],
        [0.9354, 0.9989, 0.9958, 0.4534, 0.9096, 0.9557, 0.4171, 0.5001, 0.5363,
         0.7124],
        [0.3547, 0.3152, 0.5110, 0.3731, 0.2244, 0.7978, 0.6862, 0.0864, 0.6345,
         0.2199],
        [0.2936, 0.6882, 0.8915, 0.5272, 0.8592, 0.2239, 0.3231, 0.1378, 0.5158,
         0.9745],
        [0.8234, 0.8574, 0.9026, 0.7769, 0.3570, 0.4178, 0.6860, 0.7759, 0.9328,
         0.6256],
        [0.1725, 0.2630, 0.9325, 0.0121, 0.5900, 0.0623, 0.3738, 0.8678, 0.6238,
         0.8297],
        [0.2838, 0.4735, 0.8414, 0.8203, 0.1922, 0.6867, 0.3935, 0.4368, 0.5256,
         0.4165],
        [0.2628, 0.0987, 0.4576, 0.3371, 0.8680, 0.4140, 0.8218, 0.0534, 0.5403,
         0.3331],
        [0.9242, 0.3641, 0.1100, 0.6171, 0.9360, 0.0566, 0.9823, 0.0024, 0.3436,
         0.9652],
        [0.8214, 0.6683, 0.0238, 0.6389, 0.1840, 0.0914, 0.4715, 0.3275, 0.9152,
         0.0472],
        [0